language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
  - extra-google-m2repository
  - build-tools-25.0.2
  - android-25
  licenses:
  - android-sdk-license-.+

script: ./gradlew assemble test

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - export SYSROOT=${ANDROID_NDK_HOME}/platforms/android-24/arch-x86_64
  - ln -s ${ANDROID_NDK_HOME}/platforms/android-24/arch-x86_64/usr/lib/crtbegin_so.o ${ANDROID_NDK_HOME}/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64/mips64el-linux-android/bin/ld
  - ln -s ${ANDROID_NDK_HOME}/platforms/android-24/arch-x86_64/usr/lib/crtend_so.o ld/ ${ANDROID_NDK_HOME}/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64/mips64el-linux-android/bin/ld

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
