language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
  - extra-google-m2repository
  - build-tools-25.0.2
  - android-25
  licenses:
  - android-sdk-license-.+

script: ./gradlew assemble test

before_install:
  - curl -L http://dl.google.com/android/repository/android-ndk-r14-linux-x86_64.zip -O
  - unzip -q android-ndk-r14-linux-x86_64.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r14
  - export PATH=$PATH:${ANDROID_NDK_HOME}

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/